KS-1-1
RoboticRobotnik/KotlinSprint pull request #1
Opened 2023-07-10 18:50 UTC by RoboticRobotnik

Declared 2 variables

2023-07-10 21:57 UTC, ievetrov requested changes
Привет! великолепное оформление пулл реквеста, все нейминги корректные. 

Оставил пару комментов в коду. поправь плиз. 
На всякий напомню) Новый коммит делай в эту же рабочую ветку и отправляй ссылку на этот же пулл реквест

2023-07-10 21:57 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task1.kt
> +fun main(args: Array<String>) {
комментарий про аргументы функции main(). Нам они пока не нужны (понадобятся только на курсовом проекте для токена бота).
Поэтому для чистоты кода предлагаю оставлять их пустыми

2023-07-10 21:57 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task1.kt
> +    val chisloZakazov:Int=75
согласно конвенции стиля написания кода Котлин, при объявлении типа после двоеточия ставится пробел.

а также знаки присваивания и арифметические знаки пробелом обосабливются)

2023-07-11 20:20 UTC, RoboticRobotnik commented on src/main/kotlin/Lesson1/Task1.kt
> +    val chisloZakazov:Int=75
Каким образом можно отправлять сразу несколько задач на проверку ?
Если я от мастер ветки создам 4 ветки и в каждой будет по решению не приведет ли к следующей ситуации:
1 задачу я мерджу, а в ветке со второй задачей нет данных по первой задаче и когда я замержду вторую задачу она затрёт решение по первой.

2023-07-11 20:38 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task1.kt
> +    val chisloZakazov:Int=75
Самое главное исключить вариант, когда в разных ветках будет отредактирован один и тот же файл. Это называется "конфликты". Потому что система не будет понимать какой код приоритетнее. Их можно зарезолвить и даже в рамках курсового проекта будет на это практика, но пока лучше не доводить до такого.

Сейчас такого возникнуть не должно. Ветка с определенным коммитом - это определенное состояние проекта. И гит умный, командой merge (слияние) он добавит новый файл с задачей из новой ветки в существующий пакет. Конечно, если этот файл будет иметь другое название. Это и есть безопасное слияние двух состояний проекта, где файлы не конфликтуют друг с другом. 

Еще можно упростить себе жизнь, сделав заглушки на несколько уроков вперед и самостоятельно их запушить сразу в мастер. Тогда не придется для каждой ветки создавать новые пакеты с файлом, а просто писать задачу в соответствующем.

2023-07-11 20:40 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task1.kt
> +    val chisloZakazov:Int=75
Ну и отвечая на вопрос, можно безопасно создавать ветки параллельно, но всегда обязательно от мастера. Если до этого в него был сделан мердж другой ветки, то его надо обновить (клик на ветку справа внизу в Идее и Update), чтобы изменения с сервера появились в локальном проекте

2023-07-11 20:41 UTC, ievetrov approved these changes
аппрув!

2023-07-11 21:08 UTC, merged