KS-1-5
RoboticRobotnik/KotlinSprint pull request #5
Opened 2023-07-12 16:35 UTC by RoboticRobotnik

Transformed seconds into hh:mm:ss format

2023-07-12 16:36 UTC, RoboticRobotnik commented
Не нашел более адекватного способа добавить нули

2023-07-12 20:46 UTC, ievetrov requested changes

2023-07-12 20:46 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task5.kt
> +    val minutKosmos = secundKosmos/60
арифметические знаки следует обосабливать пробелами согласно конвенции стиля Котлин

2023-07-12 20:46 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task5.kt
> +    print("%02d".format(chasKosmos)+":"+"%02d".format(ostatokChasKosmos)+":"+"%02d".format(ostatokSecundKosmos))
правильный подход, но есть пару комментов
- мы используем Котлин, а он умеет в интерполяцию. поэтому лучше ее, чем складывать строки
- форматирование можно объединить вот примерно таким образом `println(String.format("%02d:%02d:%02d", hours, minutes, seconds))`

2023-07-15 23:00 UTC, ievetrov requested changes

2023-07-15 23:00 UTC, ievetrov commented on src/main/kotlin/Lesson1/Task5.kt
> +    print(String.format("%02d:%02d:%02d",chasKosmos,ostatokChasKosmos,ostatokSecundKosmos))
хорошо! давай только еще добавим пробелы после запятых для соблюдения стиля

2023-07-16 15:17 UTC, ievetrov approved these changes
все красиво!

2023-07-17 08:59 UTC, merged